/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        Button: (typeof import("./components/button/Button.vue"))["default"];
        HeatMap: (typeof import("./components/heatMapChart/HeatMap.vue"))["default"];
        HeatMap2: (typeof import("./components/heatMapChart2/HeatMap2.vue"))["default"];
        HeatMap2D: (typeof import("./components/heatMapChart2D/HeatMap2D.vue"))["default"];
        ImageAnnotationView: (typeof import("./components/ImageAnnotationView/ImageAnnotationView.vue"))["default"];
        RadarChart: (typeof import("./components/radarChart/RadarChart.vue"))["default"];
        RouterLink: (typeof import("vue-router"))["RouterLink"];
        RouterView: (typeof import("vue-router"))["RouterView"];
    }
}
